apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuzeg5
spec:
  selector:
    matchLabels:
      app: kuzeg5label
  replicas: 3
  template:
    metadata:
      labels:
        app: kuzeg5label
    spec:
      containers:
        - name: kuzeg5web
          image: yakaktus/lb5
          ports:
            - containerPort: 1414
          resources:
            requests:
              cpu: "50m"
              memory: "1000Mi"
            limits:
              cpu: "100m"
              memory: "2000Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 1414
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 5

